server:
  port: 8088
  servlet:
    context-path: /

fast-call:
  pool:
    max-idle-connections: 50
    keep-alive-minutes: 5
  client:
    connect-timeout: 15
    read-timeout: 45
    write-timeout: 45
  cache:
    enable: false
    max-size: 10485760
  source-cache:
    enable: true
    engine: memory
    expire: 60
    refresh-when-expire: true
  forward-proxy:
    enable: true
    add-forward-header: true
    prefix: /fc_forward_proxy
    system-property: Fc-Forward-Proxy-System
  max-requests: 200
  max-requests-per-host: 20
  easy-source:
    - system:
        code: none-system
        name: 测试无认证的系统
        enable: true
        host: http://127.0.0.1:8080
      auth:
        type: NONE
        path: /
        content: |
          {
            "username": "admin",
            "password": "123456"
          }

spring:
  application:
    name: test-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fastcall-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true




