server:
  port: 8088
  servlet:
    context-path: /

fast-call:
  max-requests: 200
  max-requests-per-host: 20
  pool:
    max-idle-connections: 50
    keep-alive-minutes: 5
  client:
    connect-timeout: 15
    read-timeout: 45
    write-timeout: 45
  filter:
    enable-rate-limit: true
    enable-request-event: true
    retry:
      enable: true
      attempts: 3
      interval: 1000
  cache:
    enable: false
    max-size: 10485760
  source-cache:
    enable: true
    engine: memory
    expire: 60
    refresh-when-expire: true
  forward-proxy:
    enable: true
    add-forward-header: true
    prefix: /fc_forward_proxy
  easy-source:
    - system:
        code: local
        name: 测试系统
        enable: true
        host: http://127.0.0.1:${server.port}
        auth-type: NONE
    - system:
        code: declarative-system
        name: 声明式调用演示系统
        enable: true
        host: http://127.0.0.1:${server.port}
        auth-type: NONE
    - system:
        code: weather-system
        name: 获取天气数据系统
        enable: true
        host: https://pc5vxpedaq.re.qweatherapi.com
        auth-type: JWT
      rate-limits:
        - maximum: 30
          span: MINUTES
      auth:
        content: |
          {
            "type": "JWT",
            "positionOn": "HEADER",
            "algorithm": "Ed25519",
            "secret": "MC4CAQAwBQYDK2VwBCIEINxyQ0QWXSdqCh20hqMIsrzGEDBBF7t+I8J7/aKGVf+V",
            "issueAtOffset": -30,
            "expiresIn": 10,
            "header": {
              "alg": "EdDSA",
              "kid": "T5B8UFRR36"
            },
            "payload": {
              "sub": "248C7MFGFY",
            }
          }



spring:
  application:
    name: test-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fastcall-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true




